version: 2
jobs:
  build:
    context: Personal
    working_directory: ~/temp
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
       # build the application image
      - run: docker build -t deriveddev/musictool:$CIRCLE_BRANCH .
      - run: docker push deriveddev/musictool:$CIRCLE_BRANCH
      - run: echo ~/.ssh/id_rsa.pub
      # - run: ssh root@138.68.137.60 'docker stop $(docker ps -aq)'
      # - run: ssh root@138.68.137.60 'docker-start musictool $CIRCLE_BRANCH'