version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t deriveddev/musictool:$CIRCLE_SHA1 .
      - run: docker push deriveddev/musictool:$CIRCLE_SHA1
  deploy-dev:
    machine: 
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "3b:21:b4:5d:7e:ac:39:fd:46:cf:aa:1b:84:aa:39:89"
      - run: ssh $SSH_USER@$SERVER_DEV 'docker stop $(docker ps -aq)'
      - run: ssh $SSH_USER@$SERVER_DEV "docker-start musictool $CIRCLE_SHA1"
  deploy-live:
    machine: 
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "3b:21:b4:5d:7e:ac:39:fd:46:cf:aa:1b:84:aa:39:89"
      - run: ssh $SSH_USER@$SERVER_LIVE 'docker stop $(docker ps -aq)'
      - run: ssh $SSH_USER@$SERVER_LIVE "docker-start musictool $CIRCLE_SHA1"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only: develop
      - deploy-live:
          requires:
            - build
          filters:
            branches:
              only: master


