version: 2
jobs:
  build:
    context: Personal
    working_directory: ~/temp
    machine: true
    steps:

      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
       # build the application image
      - run: docker build -t deriveddev/musictool:$CIRCLE_SHA1 .
      - run: docker push deriveddev/musictool:$CIRCLE_SHA1
  deploy:
    machine: 
      enabled: true
    steps:
      - add_ssh_keys:
        fingerprints:
          - "3b:21:b4:5d:7e:ac:39:fd:46:cf:aa:1b:84:aa:39:89"
      - run: ssh root@138.68.137.60 'docker stop $(docker ps -aq)'
      - run: ssh root@138.68.137.60 'docker-start musictool $CIRCLE_SHA1'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
        requires:
          -build
          filters:
            branches:
              only: develop


